<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>td</string>
   </array>
  <key>name</key>
  <string>td</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.td</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#internal</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>([A-Za-z][A-Za-z0-9_.]*)\s*(\(\w+\))?\s*(\{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.td</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>constant.numeric.td</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>punctuation.td</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.td</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\[)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.td</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\])</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.td</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\&lt;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.td</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__3</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\&gt;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.td</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b\w+ +)(\w+\b)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>normal.td</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>keyword.td</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(#.*)</string>
          <key>name</key>
          <string>comment.td</string>
        </dict>
       </array>
    </dict>
    <key>internal</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(integer|string|boolean)</string>
          <key>name</key>
          <string>keyword.td</string>
        </dict>
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\()(\w+)(\))</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.td</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>keyword.td</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>punctuation.td</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>main__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\w+)</string>
          <key>name</key>
          <string>keyword.td</string>
        </dict>
       </array>
    </dict>
    <key>main__3</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#internal</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(, *)(\w*)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.td</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>keyword.td</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
